"""Init db

Revision ID: f6352590ad32
Revises: 
Create Date: 2025-06-09 23:14:38.323939

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f6352590ad32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('salary_from', sa.String(), nullable=True),
    sa.Column('salary_to', sa.String(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('employment', sa.String(), nullable=True),
    sa.Column('metro', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('employer_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancies')
    op.drop_table('users')
    # ### end Alembic commands ###
